### ISSUE TITLE
How to get the .env and db connection strings

### ISSUE THREAD

**Issue by SH20RAJ** [tripathics/alumni-portal-client#20]
- [ ] Where to get the db connection string or is it possible to edit and contribute to the project with/without getting the environment variable of two separate client and server code bases ????
- [ ] Maybe Login with Google can be added ( if we will use NextAuth ) for OTP less registration

**Comment by tripathics** [comment]
There's a .env.example file. you can copy it to a .env file and specify the values. Let's discuss this on the whatsapp group
